[WIP] feat: added flag (--inspect)
metacall/deploy pull request #30
Opened 2022-02-18 11:12 UTC by Creatoon

#### Short description of what this resolves:

With this pull request, you can look at all of your deployments on FAAS.

#### How it works:

1) Open your terminal & hit the command given below:-

```js
$ metacall-deploy  --inspect
```

#### Screenshots

![WhatsApp Image 2022-02-18 at 10 11 13 PM](https://user-images.githubusercontent.com/65965202/154729313-3c86359f-832e-485e-83e8-c3dcd122a202.jpeg)

![WhatsApp Image 2022-02-18 at 10 11 50 PM](https://user-images.githubusercontent.com/65965202/154729321-e882ec66-0e0c-4be4-b6a7-c8d065b55937.jpeg)

- [x] My branch is up-to-date with the Upstream `master` branch.

2022-02-18 12:55 UTC, Siddhant-K-code commented on src/index.ts
> +		}
```suggestion
		inspect: { type: Boolean, alias: 'i', defaultValue: false }
```

2022-02-18 13:00 UTC, Siddhant-K-code reviewed
Marking `inspect` as optional or not.

@viferga what will be better way?

2022-02-18 17:03 UTC, Creatoon commented on src/index.ts
> +	inspect: boolean;
@Siddhant-K-code thanks for pointing this out, it should be optional.

2022-02-19 03:49 UTC, Siddhant-K-code requested changes
Just a Formatting Change

2022-02-19 03:49 UTC, Siddhant-K-code commented on src/index.ts
> +		}
Keep Formatting same as #L113
```suggestion
		inspect: { type: Boolean, alias: 'i', defaultValue: false, optional: true }
```

2022-02-20 12:01 UTC, Siddhant-K-code approved these changes
LGTM ✨ 

Thanks for the PR 🚀

2022-02-20 12:17 UTC, Creatoon commented
> LGTM sparkles
> 
> Thanks for the PR rocket

Hey, this pr isn't completed yet, please look at the title [WIP]

2022-02-20 18:37 UTC, merged